--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version: P.20131013
--  \   \         Application: netgen
--  /   /         Filename: .vhd
-- /___/   /\     Timestamp: Mon Mar 28 20:28:34 2016
-- \   \  /  \ 
--  \___\/\___\
--             
-- Command	: -intstyle ise -ar Structure -tm ALU_Toplevel -w -dir netgen/synthesis -ofmt vhdl -sim ALU_Toplevel.ngc ALU_Toplevel_synthesis.vhd 
-- Device	: xc3s500e-4-fg320
-- Input file	: ALU_Toplevel.ngc
-- Output file	: /home/robert/Github/UMD_RISC-16G5/ALU/ALU/netgen/synthesis/ALU_Toplevel_synthesis.vhd
-- # of Entities	: 1
-- Design Name	: ALU_Toplevel
-- Xilinx	: /opt/Xilinx/14.7/ISE_DS/ISE/
--             
-- Purpose:    
--     This VHDL netlist is a verification model and uses simulation 
--     primitives which may not represent the true implementation of the 
--     device, however the netlist is functionally correct and should not 
--     be modified. This file cannot be synthesized and should only be used 
--     with supported simulation tools.
--             
-- Reference:  
--     Command Line Tools User Guide, Chapter 23
--     Synthesis and Simulation Design Guide, Chapter 6
--             
--------------------------------------------------------------------------------

